language: python
python: 3.6
before_install:
  - sudo apt-get install octave
install:
  - pip install -r requirements.txt
  - pip install oct2py codecov
script:
  - pytest -W --cov=./
  - codecov --token=745851ac-d7de-48ae-b84c-22240114e57a